// examples/sample-vue/src/components/Button.vue
<template>
  <button
    :class="['btn', `btn-${variant}`, { 'btn-loading': loading }]"
    :disabled="disabled || loading"
    @click="handleClick"
  >
    <span v-if="loading" class="spinner"></span>
    <slot v-else></slot>
  </button>
</template>

<script setup lang="ts">
/**
 * A reusable button component with multiple variants and loading state
 *
 * @component
 * @example
 * ```vue
 * <Button variant="primary" @click="handleSubmit">
 *   Click me
 * </Button>
 * ```
 */

interface Props {
  /** The button style variant */
  variant?: 'primary' | 'secondary' | 'danger' | 'ghost';
  /** Whether the button is disabled */
  disabled?: boolean;
  /** Whether the button is in loading state */
  loading?: boolean;
}

interface Emits {
  /** Emitted when button is clicked */
  (e: 'click', event: MouseEvent): void;
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'primary',
  disabled: false,
  loading: false,
});

const emit = defineEmits<Emits>();

/**
 * Handles button click event
 * @param event - The mouse click event
 */
const handleClick = (event: MouseEvent) => {
  if (!props.disabled && !props.loading) {
    emit('click', event);
  }
};
</script>

<style scoped>
.btn {
  padding: 0.5rem 1rem;
  border-radius: 0.375rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
}

.btn-primary {
  background-color: #3b82f6;
  color: white;
}

.btn-secondary {
  background-color: #6b7280;
  color: white;
}

.btn-danger {
  background-color: #ef4444;
  color: white;
}

.btn-ghost {
  background-color: transparent;
  border: 1px solid #d1d5db;
}

.btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.btn-loading {
  position: relative;
  color: transparent;
}

.spinner {
  position: absolute;
  width: 1rem;
  height: 1rem;
  border: 2px solid rgba(255, 255, 255, 0.3);
  border-top-color: white;
  border-radius: 50%;
  animation: spin 0.6s linear infinite;
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
</style>

// examples/sample-svelte/src/lib/Button.svelte
<script>
  import { createEventDispatcher } from 'svelte';

  /**
   * Button variant type
   * @type {'primary' | 'secondary' | 'danger'}
   */
  export let variant = 'primary';

  /**
   * Button size
   * @type {'small' | 'medium' | 'large'}
   */
  export let size = 'medium';

  /**
   * Disabled state
   */
  export let disabled = false;

  /**
   * Button label text
   */
  export let label = 'Click me';

  const dispatch = createEventDispatcher();

  /**
   * Handle button click event
   */
  function handleClick() {
    if (!disabled) {
      dispatch('click', { variant, size });
    }
  }

  // Reactive statement to compute button classes
  $: classes = `btn btn-${variant} btn-${size} ${disabled ? 'disabled' : ''}`;
</script>

<button
  class={classes}
  {disabled}
  on:click={handleClick}
>
  {label}
  <slot />
</button>

<style>
  .btn {
    padding: 0.5rem 1rem;
    border: none;
    border-radius: 0.25rem;
    cursor: pointer;
    font-weight: 500;
    transition: all 0.2s;
  }

  .btn-primary {
    background-color: #007bff;
    color: white;
  }

  .btn-secondary {
    background-color: #6c757d;
    color: white;
  }

  .btn-danger {
    background-color: #dc3545;
    color: white;
  }

  .btn-small {
    font-size: 0.875rem;
    padding: 0.25rem 0.5rem;
  }

  .btn-medium {
    font-size: 1rem;
  }

  .btn-large {
    font-size: 1.125rem;
    padding: 0.75rem 1.5rem;
  }

  .disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }
</style>
